version: '3'
services:
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - MONGODB_URI=mongodb://db:27017/movie_manager_production
    depends_on:
      - db

volumes:
  mongo-data:
