development:
  clients:
    default:
      database: movie_manager_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: movie_manager_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: movie_manager_production
      hosts:
        - db:27017
      options:
        server_selection_timeout: 5
  options:
    raise_not_found_error: false
